apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
  namespace: test
spec:
  containers:
  - image: busybox
    name: busybox
    args:
    - sleep
    - "1000"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
