apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxx
  name: busyboxx
  namespace: test
spec:
  containers:
  - image: busybox
    name: busyboxx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
