---
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  repositories: |
    - type: helm
      name: stable
      url: https://charts.helm.sh/stable
    - type: helm
      name: argo-cd
      url: https://argoproj.github.io/argo-helm
  timeout.reconciliation: 15s
  url: https://argocd.example.com
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  #   meta.helm.sh/release-name: argo-cd
  #   meta.helm.sh/release-namespace: argocd
  # labels:
  #   app.kubernetes.io/component: server
  #   app.kubernetes.io/instance: argo-cd
  #   app.kubernetes.io/managed-by: Helm
  #   app.kubernetes.io/name: argocd-cm
  #   app.kubernetes.io/part-of: argocd
  #   argocd.argoproj.io/instance: argo-cd
  #   helm.sh/chart: argo-cd-3.17.6
  name: argocd-cm
  namespace: argocd
