apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  project: default
  source:
    chart: grafana
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
            ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          path: /
          hosts:
            - tbd_grafana_hostname_eks_dns_ext
          tls:
            - secretName: tbd_grafana_hostname_secret
              hosts:
                - 'tbd_grafana_hostname_eks_dns_ext'
        env:
          GF_SERVER_ROOT_URL: https://tbd_grafana_hostname_eks_dns_ext
          GF_AUTH_ANONYMOUS_ENABLED: false
          GF_USERS_ALLOW_SIGN_UP: false
          GF_AUTH_DISABLE_LOGIN_FORM: false
          GF_AUTH_OAUTH_AUTO_LOGIN: false
          GF_AUTH_GENERIC_OAUTH_NAME: Okta
          GF_AUTH_GENERIC_OAUTH_ENABLED: true
          GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email groups"
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: tbd_GRAFANA_AUTH_GENERIC_OAUTH_CLIENT_ID
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: tbd_GRAFANA_GENERIC_OAUTH_CLIENT_SECRET
          GF_AUTH_GENERIC_OAUTH_AUTH_URL: tbd_okta_domain_url_/oauth2/v1/authorize
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: tbd_okta_domain_url_/oauth2/v1/token
          GF_AUTH_GENERIC_OAUTH_API_URL: tbd_okta_domain_url_/oauth2/v1/userinfo
          GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: tbd_grafana_auth_gen_oauth_role_attribute_path
        grafana.ini:
          paths:
            data: /var/lib/grafana/data
            logs: /var/log/grafana
            plugins: /var/lib/grafana/plugins
            provisioning: /etc/grafana/provisioning
          analytics:
            check_for_updates: true
          log:
            mode: console
          grafana_net:
            url: https://grafana.net
        sidecar:
          image:
            tag: 1.10.16
          imagePullPolicy: IfNotPresent
          resources:
           limits:
             cpu: 300m
             memory: 300Mi
           requests:
             cpu: 100m
             memory: 100Mi
          dashboards:
            enabled: true
            # label that the configmaps with dashboards are marked with
            label:  grafana_dashboard
            # folder in the pod that should hold the collected dashboards (unless `defaultFolderName` is set)
            folder: /tmp/dashboards
            # The default folder name, it will create a subfolder under the `folder` and put dashboards in there instead
            defaultFolderName: null
            # If specified, the sidecar will search for dashboard config-maps inside this namespace.
            # Otherwise the namespace in which the sidecar is running will be used.
            # It's also possible to specify ALL to search in all namespaces
            searchNamespace: monitoring
            # provider configuration that lets grafana manage the dashboards
            provider:
              # name of the provider, should be unique
              name: sidecarProvider
              # orgid as configured in grafana
              orgid: 1
              # folder in which the dashboards should be imported in grafana
              folder: ''
              # type of the provider
              type: file
              # disableDelete to activate a import-only behaviour
              disableDelete: false
          datasources:
            enabled: true
            # label that the configmaps with datasources are marked with
            label: grafana_datasource
            # If specified, the sidecar will search for datasource config-maps inside this namespace.
            # Otherwise the namespace in which the sidecar is running will be used.
            # It's also possible to specify ALL to search in all namespaces
            searchNamespace: monitoring
        nodeSelector:
            beta.kubernetes.io/os: linux

    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.4.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
