apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
        fullnameOverride: ingress-nginx-internal
        controller:
          config:
            use-proxy-protocol: "true"
          ingressClass: nginx-internal
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"
          scope:
            namespace: ingress-nginx
          service:
            annotations:
              domainName: '*.main.use1.k8s.mgnt-xspdev.in' #TBA
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
              service.beta.kubernetes.io/aws-load-balancer-internal-additional-resource-tags: delivery=xspdev,Name=nginx-ingress-main-use1-xspdev
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
              service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0d6df32f2af3f2ca0 #TBA
            externalTrafficPolicy: Local
            labels:
              dns: route53 #TBA
              nginx-ingress-type: internal
            omitClusterIP: true
        defaultBackend:
          service:
            omitClusterIP: true
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 3.23.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
