apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prereqs
  project: default
  source:
    chart: metrics-server
    helm:
      values: |
        nodeSelector:
            beta.kubernetes.io/os: linux
        ## API service parameters
        ##
        apiService:
          ## Specifies whether the v1beta1.metrics.k8s.io API service should be created
          ## This should not be necessary in k8s version >= 1.8, but depends on vendors and cloud providers.
          ##
          create: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.5.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
