apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prereqs
  project: default
  source:
    chart: kube-state-metrics
    helm:
      values: |
        nodeSelector:
            beta.kubernetes.io/os: linux
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 3.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
