argo-cd:
  dex:
    enabled: false
  server:
    # extraArgs:
    #   - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

  configs:
    secret:
      # Argo expects the password in the secret to be bcrypt hashed.
      # You can create this hash with https://bcrypt.online/
      argocdServerAdminPassword: "$2y$10$iMc33yOUT8oJWhwvoxqf9.TAsDQ5FRpF0iShYxiptJkR9hfC4f666"
